NAME: '.sm08'

DATASET:
  TYPE: 'pedes'
  NAME: 'UPAR'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 224 #256
  WIDTH: 224 #128
  PHASE1_ROOT_PATH: '/media/sdd/lx/dataset/data/phase1/annotations/phase1/'
  PHASE2_ROOT_PATH: '/media/sdd/lx/dataset/data/phase2/'
  ROOT_PATH: '/media/sdd/lx/dataset/data/'

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  TYPE: 'swin_b' # swin_t/s/b

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 32
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 0.0
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.00001 #1e-3
    LR_NEW: 0.00001 #1e-3
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
